name: PluginDownloader
version: 1.0.0
main: com.gordey25690.plugindownloader.PluginDownloader
api-version: "1.21"
authors: [gordey25690, DeepSeek]
description: Плагин для загрузки и управления другими плагинами
website: https://github.com/gordey9992

commands:
  plugindownloader:
    description: Основная команда плагина
    usage: /<command> <install|list|remove|update|info|search|reload|sync>
    aliases: [пдл, плагины, pdl]
  магазинплагинов:
    description: Открыть магазин плагинов
    usage: /<command> [поиск]
    aliases: [мп, pluginmarket]
  обновлениеплагинов:
    description: Проверить обновления плагинов
    usage: /<command> [все|плагин]
    aliases: [оп, pluginupdate]

permissions:
  plugindownloader.*:
    description: Все разрешения плагина
    children:
      plugindownloader.use: true
      plugindownloader.install: true
      plugindownloader.remove: true
      plugindownloader.update: true
      plugindownloader.reload: true
      plugindownloader.sync: true
  
  plugindownloader.use:
    description: Основное разрешение на использование
    default: op
  
  plugindownloader.install:
    description: Установка плагинов
    default: op
  
  plugindownloader.remove:
    description: Удаление плагинов
    default: op
  
  plugindownloader.update:
    description: Обновление плагинов
    default: op
  
  plugindownloader.reload:
    description: Перезагрузка конфигурации
    default: op
  
  plugindownloader.sync:
    description: Синхронизация плагинов
    default: op
